import type { Profile } from "@/lib/types/profile";

// --- Admin user ---
export const DUMMY_ADMIN: Profile = {
  id: "profile-admin",
  email: "admin@kaist.ac.kr",
  full_name: "김관리",
  display_name: "관리자김",
  phone: "650-000-0001",
  role: "admin",
  kaist_bs_year: 2005,
  kaist_bs_major: "전산학",
  is_integrated_ms_phd: false,
  kaist_ms_year: null,
  kaist_ms_major: null,
  kaist_phd_year: 2010,
  kaist_phd_major: "전산학",
  company: "Google",
  job_title: "Director of Engineering",
  venmo_handle: "@admin-kim",
  zelle_handle: "admin@kaist.ac.kr",
  created_at: "2024-01-01T00:00:00Z",
  updated_at: "2024-01-01T00:00:00Z",
};

// --- Regular members (3 people) ---
export const DUMMY_MEMBERS: Profile[] = [
  {
    id: "profile-member-1",
    email: "member1@gmail.com",
    full_name: "이철수",
    display_name: "철수",
    phone: "650-111-1111",
    role: "member",
    kaist_bs_year: 2010,
    kaist_bs_major: "전기및전자공학",
    is_integrated_ms_phd: false,
    kaist_ms_year: 2012,
    kaist_ms_major: "전기및전자공학",
    kaist_phd_year: null,
    kaist_phd_major: null,
    company: "Apple",
    job_title: "Senior Software Engineer",
    venmo_handle: "@chulsoo",
    zelle_handle: null,
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "profile-member-2",
    email: "member2@gmail.com",
    full_name: "박영희",
    display_name: "영희",
    phone: "650-222-2222",
    role: "member",
    kaist_bs_year: 2012,
    kaist_bs_major: "수리과학",
    is_integrated_ms_phd: true,
    kaist_ms_year: null,
    kaist_ms_major: null,
    kaist_phd_year: 2018,
    kaist_phd_major: "수리과학",
    company: "Meta",
    job_title: "Data Scientist",
    venmo_handle: "@younghee-p",
    zelle_handle: "member2@gmail.com",
    created_at: "2024-03-01T00:00:00Z",
    updated_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "profile-member-3",
    email: "member3@gmail.com",
    full_name: "최민준",
    display_name: "민준",
    phone: "650-333-3333",
    role: "member",
    kaist_bs_year: 2015,
    kaist_bs_major: "기계공학",
    is_integrated_ms_phd: false,
    kaist_ms_year: null,
    kaist_ms_major: null,
    kaist_phd_year: null,
    kaist_phd_major: null,
    company: "Tesla",
    job_title: "Mechanical Engineer",
    venmo_handle: null,
    zelle_handle: "member3@gmail.com",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
];

// --- Pending user (waiting for admin approval) ---
export const DUMMY_PENDING: Profile = {
  id: "profile-pending-1",
  email: "newbie@gmail.com",
  full_name: "신입생",
  display_name: "신입",
  phone: "650-999-9999",
  role: "pending",
  kaist_bs_year: 2022,
  kaist_bs_major: "전산학",
  is_integrated_ms_phd: false,
  kaist_ms_year: null,
  kaist_ms_major: null,
  kaist_phd_year: null,
  kaist_phd_major: null,
  company: "Startup",
  job_title: "Software Engineer",
  venmo_handle: "@newbie",
  zelle_handle: null,
  created_at: "2026-03-05T00:00:00Z",
  updated_at: "2026-03-05T00:00:00Z",
};

// Simulates the currently logged-in user. Uses the first member as the default.
export const CURRENT_USER = DUMMY_MEMBERS[0];

// All profiles combined for convenience
export const ALL_PROFILES: Profile[] = [
  DUMMY_ADMIN,
  ...DUMMY_MEMBERS,
  DUMMY_PENDING,
];
